import { CategoryMeta } from '@/types/transaction';

export const CATEGORY_LIST: CategoryMeta[] = [
  // KHOẢN THU
  {
    id: 'salary',
    label: 'Lương',
    type: 'income',
    icon: 'dollar-sign',
    color: '#1ABC9C',
    description: 'Thu nhập cố định hàng tháng',
  },
  {
    id: 'freelance',
    label: 'Freelance',
    type: 'income',
    icon: 'briefcase',
    color: '#2ECC71',
    description: 'Dự án phụ và hoa hồng',
  },
  {
    id: 'bonus',
    label: 'Thưởng',
    type: 'income',
    icon: 'award',
    color: '#F1C40F',
    description: 'Tiền thưởng, hoa hồng',
  },
  {
    id: 'investment',
    label: 'Đầu tư',
    type: 'income',
    icon: 'trending-up',
    color: '#27AE60',
    description: 'Lãi từ đầu tư, cổ tức',
  },
  {
    id: 'gift',
    label: 'Quà tặng',
    type: 'income',
    icon: 'gift',
    color: '#E67E22',
    description: 'Tiền mừng, quà tặng',
  },
  {
    id: 'rental',
    label: 'Cho thuê',
    type: 'income',
    icon: 'home',
    color: '#16A085',
    description: 'Thu nhập từ cho thuê',
  },
  {
    id: 'business',
    label: 'Kinh doanh',
    type: 'income',
    icon: 'shopping-cart',
    color: '#2980B9',
    description: 'Lợi nhuận kinh doanh',
  },
  {
    id: 'refund',
    label: 'Hoàn tiền',
    type: 'income',
    icon: 'refresh-cw',
    color: '#95A5A6',
    description: 'Hoàn tiền, bồi hoàn',
  },

  // KHOẢN CHI
  {
    id: 'food',
    label: 'Ăn uống',
    type: 'expense',
    icon: 'coffee',
    color: '#E74C3C',
    description: 'Bữa ăn, cafe, trà sữa',
  },
  {
    id: 'transport',
    label: 'Đi lại',
    type: 'expense',
    icon: 'navigation',
    color: '#9B59B6',
    description: 'Xe bus, taxi, xăng xe',
  },
  {
    id: 'home',
    label: 'Nhà cửa',
    type: 'expense',
    icon: 'home',
    color: '#3498DB',
    description: 'Tiền thuê, sửa chữa',
  },
  {
    id: 'shopping',
    label: 'Mua sắm',
    type: 'expense',
    icon: 'shopping-bag',
    color: '#F39C12',
    description: 'Quần áo, giày dép, phụ kiện',
  },
  {
    id: 'health',
    label: 'Sức khỏe',
    type: 'expense',
    icon: 'activity',
    color: '#C0392B',
    description: 'Thuốc men, khám bệnh',
  },
  {
    id: 'education',
    label: 'Giáo dục',
    type: 'expense',
    icon: 'book',
    color: '#8E44AD',
    description: 'Học phí, sách vở',
  },
  {
    id: 'travel',
    label: 'Du lịch',
    type: 'expense',
    icon: 'map-pin',
    color: '#16A085',
    description: 'Vé máy bay, khách sạn',
  },
  {
    id: 'utilities',
    label: 'Hóa đơn',
    type: 'expense',
    icon: 'zap',
    color: '#D35400',
    description: 'Điện, nước, internet',
  },
  {
    id: 'entertainment',
    label: 'Giải trí',
    type: 'expense',
    icon: 'film',
    color: '#E91E63',
    description: 'Phim ảnh, game, âm nhạc',
  },
  {
    id: 'sport',
    label: 'Thể thao',
    type: 'expense',
    icon: 'heart',
    color: '#FF5722',
    description: 'Gym, yoga, thể thao',
  },
  {
    id: 'beauty',
    label: 'Làm đẹp',
    type: 'expense',
    icon: 'scissors',
    color: '#FF4081',
    description: 'Cắt tóc, spa, mỹ phẩm',
  },
  {
    id: 'phone',
    label: 'Điện thoại',
    type: 'expense',
    icon: 'smartphone',
    color: '#607D8B',
    description: 'Cước điện thoại, data',
  },
  {
    id: 'insurance',
    label: 'Bảo hiểm',
    type: 'expense',
    icon: 'shield',
    color: '#009688',
    description: 'Bảo hiểm y tế, xe',
  },
  {
    id: 'pet',
    label: 'Thú cưng',
    type: 'expense',
    icon: 'heart',
    color: '#795548',
    description: 'Thức ăn, chăm sóc pet',
  },
  {
    id: 'charity',
    label: 'Từ thiện',
    type: 'expense',
    icon: 'heart',
    color: '#4CAF50',
    description: 'Quyên góp, từ thiện',
  },
  {
    id: 'debt',
    label: 'Trả nợ',
    type: 'expense',
    icon: 'credit-card',
    color: '#F44336',
    description: 'Trả nợ, trả góp',
  },
  {
    id: 'family',
    label: 'Gia đình',
    type: 'expense',
    icon: 'users',
    color: '#673AB7',
    description: 'Chu cấp gia đình',
  },
  {
    id: 'electronics',
    label: 'Điện tử',
    type: 'expense',
    icon: 'cpu',
    color: '#00BCD4',
    description: 'Laptop, điện thoại, máy tính',
  },

  // CHUNG
  {
    id: 'others',
    label: 'Khác',
    type: 'common',
    icon: 'grid',
    color: '#7F8C8D',
    description: 'Chi tiêu khác',
  },
];

export const DEFAULT_WALLETS = [
  'Ví tiền mặt',
  'Thẻ tín dụng',
  'Tài khoản ngân hàng',
];
